name: "tim's cicd scan"

on: 
  workflow_dispatch

jobs:
  container_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Wiz CLI
        run: |
         curl -o wizcli https://wizcli.app.wiz.io/wizcli
         chmod +x wizcli
         
      - name: Authenticate to the Wiz API
        run: |
         ./wizcli auth --id ${{ secrets.WIZ_CLIENT_ID }} --secret ${{ secrets.WIZ_CLIENT_SECRET }}

      - name: Build an image from Dockerfile
        run: |
          cd container-fail
          docker build -t docker.io/tim4wiz/wizdemo:1.0 .
         
      - name: Scan Docker Image
        run: |
         ./wizcli docker scan --image docker.io/tim4wiz/wizdemo:1.0 --policy tim_container_test --policy-hits-only
         
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: tim4wiz
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Push an image to Docker Hub
        run: |
          docker push docker.io/tim4wiz/wizdemo:1.0

  IaC_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Wiz CLI & Authenticate
        run: |
         cd aws/terraform-eks-fail
         curl -o wizcli https://wizcli.app.wiz.io/wizcli
         chmod +x wizcli
         ./wizcli auth --id ${{ secrets.WIZ_CLIENT_ID }} --secret ${{ secrets.WIZ_CLIENT_SECRET }}
         
      - name: Scan IaC
        run: |
         cd aws/terraform-eks-fail
         ./wizcli iac scan --path terraform.tf --parameter-files variables.tf --policy tim_yurch_iac_test
